name: publish
on:
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps: 
      - name: Checkout
        uses: action/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with: 
          images: ghcr.io/rizki-rianto666/belajar-CI-CD
          tags: latest
      - name: Login to GHCR
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: lint-dockerfile
        uses: hadolint/hadolint-action@3.1.0
        with: 
          dockerfile: Dockerfile
      - name: Build Container
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          labels: ${{steps.meta.output.labels}}
          tags: ${{steps.meta.output.labels}}, ghcr.io/rizki-rianto666/belajar-CI-CD:latest
          
